#!/usr/bin/python

import pygame
import smbus

bus = smbus.SMBus(1)
addressMega = 0x09
addressNanoRarm = 0x0b

timeout = 1

def writeData(value):
        byteValue = StringToBytes(value)
        bus.write_i2c_block_data(addressMega,0x00,byteValue) #first byte is 0=command >

        bus.write_i2c_block_data(addressNanoRarm,0x00,byteValue) #first byte is 0=comm>

def StringToBytes(val):
            retVal = []
            for c in val:
                    retVal.append(ord(c))
            return retVal


def main():

    left = 0
    right = 0
    negLeft = 0
    negRight = 0
    directionLeft = " "
    directionRight = " "
    motorSpeed_L = 0
    motorSpeed_R = 0
    trigger_L = 0
    trigger_R = 0
    pygame.init()


    # This dict can be left as-is, since pygame will generate a
    # pygame.JOYDEVICEADDED event for every joystick connected
    # at the start of the program.
    joysticks = {}

    done = False
    while not done:
        # Event processing step.
        # Possible joystick events: JOYAXISMOTION, JOYBALLMOTION, JOYBUTTONDOWN,
        # JOYBUTTONUP, JOYHATMOTION, JOYDEVICEADDED, JOYDEVICEREMOVED
        for event in pygame.event.get():

            if event.type == pygame.QUIT:
                done = True  # Flag that we are done so we exit this loop.

            if event.type == pygame.JOYBUTTONDOWN:

               if event.button == 11:
                  writeData("armUp")

               if event.button == 12:
                  writeData ("armDown")

               if event.button == 6:
                  writeData ("lighton")

               if event.button == 15:
                  writeData ("lightoff")

               if event.button == 0:
                  writeData ("allmotors;stop")


            if event.type == pygame.JOYDEVICEADDED:
                    joy = pygame.joystick.Joystick(event.device_index)
                    joysticks[joy.get_instance_id()] = joy
                    print(f"Joystick {joy.get_instance_id()} connencted")

            if event.type == pygame.JOYDEVICEREMOVED:
                    del joysticks[event.instance_id]



            if event.type == pygame.JOYAXISMOTION:

                x_axis = joystick.get_axis(0)  # Left joystick X-axis
                y_axis = joystick.get_axis(1)  # Left joystick Y-axis

                trigger_L = joystick.get_axis(4)  # Left trigger
                trigger_R = joystick.get_axis(5)  # right trigger

                x_axis = x_axis * 255
                y_axis = y_axis * 255
                trigger_L = (trigger_L + 1) * 127
                trigger_R = (trigger_R  + 1) * 127

                x_axis = round(x_axis)
                y_axis = round(y_axis)

                motorSpeed = abs(y_axis)

                if y_axis < 0:
                    directionRight = "forward"
                    directionLeft = "forward"

                if y_axis > 0:
                    directionRight = "reverse"
                    directionLeft = "reverse"

                if abs(y_axis) < 20:
                    directionRight = "stopped"
                    directionLeft = "stopped"
                motorSpeed = abs(y_axis)

                if x_axis < 0:
                    turnDir = "Left"

                if x_axis > 0:
                    turnDir = "Right"

                if abs(x_axis) < 20:
                    turnDir = "centered"

                if turnDir == "Left":
                    motorSpeed_L = motorSpeed - abs(x_axis)
                    motorSpeed_R = motorSpeed 

                if turnDir == "Right":
                    motorSpeed_L = motorSpeed
                    motorSpeed_R = motorSpeed - abs(x_axis) 

                if motorSpeed_L < 16:
                    motorSpeed_L = 0


                if motorSpeed_R < 16:
                    motorSpeed_R = 0


                if turnDir == "centered":
                    motorSpeed_L = motorSpeed
                    motorSpeed_R = motorSpeed


                if directionRight == "stopped" and turnDir == "centered":
                    writeData ("allmotors;stop")


                writeData("motor2;" + directionLeft + ";" + str(motorSpeed_R))
                writeData("motor3;" + directionLeft + ";" + str(motorSpeed_R))
                writeData("motor1;" + directionRight + ";" + str(motorSpeed_L))
                writeData("motor4;" + directionRight + ";" + str(motorSpeed_L))


            pygame.event.clear()

        joystick_count = pygame.joystick.get_count()

        for joystick in joysticks.values():
            jid = joystick.get_instance_id()

            name = joystick.get_name()

            guid = joystick.get_guid()

            power_level = joystick.get_power_level()
            axes = joystick.get_numaxes()

            buttons = joystick.get_numbuttons()


            for i in range(buttons):
                button = joystick.get_button(i)


            hats = joystick.get_numhats()

            for i in range(hats):
                hat = joystick.get_hat(i)


if __name__ == "__main__":
    main()
    # If you forget this line, the program will 'hang'
    # on exit if running from IDLE.
    pygame.quit()
